### ISSUE TITLE
Hostile mobs Spawning in peaceful biomes

### ISSUE THREAD

**Issue by ShyNieke** [Nitespring/MonsterPlus#1]
Hi there,

it seems like the hostile mobs of monster plus are spawning in biomes that hostile mobs should not spawn in.

examples of affected biomes are:
Mushroom fields
deep dark

This can cause for a lot of trouble especially with them spawning in the deep dark.
I want to suggest either the removal of the mobs spawning in these types of biomes or making it a config option if they can spawn in "peaceful biomes"

greetings Shy

**Comment by BugmanBugman** [comment]
I would like to concur

**Comment by TelepathicGrunt** [comment]
In addition, this mod adds monsters to forge tagged biomes in `forge:no_default_monsters` which are supposed to be biomes with no monster spawns.
![image](https://github.com/Nitespring/MonsterPlus/assets/40846040/14ece563-e9a5-47ff-b45c-fc984b5de94b)

https://github.com/AlexModGuy/AlexsCaves/blob/main/src/main/resources/data/forge/tags/worldgen/biome/no_default_monsters.json

Add a check to not add the monsters to those tagged biomes and should be golden for modded biomes.

**Comment by Nitespring** [comment]
I removed them from the vanilla biomes in the new version for 1.21 (I will update 1.20.1 later and maybe prior versions).
I will also remove spawns from biomes in the forge/neoforge tag next version
